function createfigure(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 14-Feb-2017 23:25:31

% Create figure
figure1 = figure('PaperOrientation','landscape','PaperUnits','normalized');

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'DisplayName','Linearized Model Values','LineStyle','--',...
    'Color',[1 0 0]);
set(plot1(2),'DisplayName','Real (Simulated) Values');

% Create xlabel
xlabel('Time (seconds)','FontSize',13.2);

% Create title
title('Angular Velocity 1 v. Time','FontSize',13.2);

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',12);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'FontSize',10.8);

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',2);
set(plot2(1),'LineStyle','--','Color',[1 0 0]);

% Create xlabel
xlabel('Time (seconds)','FontSize',13.2);

% Create title
title('Angular Velocity 2 v. Time','FontSize',13.2);

% Create ylabel
ylabel('Angular Velocity (radians/second)','FontSize',13.2);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0.0025165109827507 0.749060289784594]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-0.163042671172318 0.57185992623028]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',12);
% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix1,'Parent',subplot3,'LineWidth',2);
set(plot3(1),'LineStyle','--','Color',[1 0 0]);

% Create xlabel
xlabel('Time (seconds)','FontSize',13.2);

% Create title
title('Angular Velocity 3 v. Time','FontSize',13.2);

box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',12);
